import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type BillTransactionDocument = BillTransaction & Document;

/**
 * Tracks every bill payment (airtime, data, cable, electricity) made by a
 * user via the external bill payment server. Created alongside a wallet
 * BILL_PAYMENT transaction for full audit trail.
 */
@Schema({ timestamps: true })
export class BillTransaction {
  _id!: Types.ObjectId;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
  user!: Types.ObjectId;

  /** 'airtime' | 'data' | 'cable' | 'electricity' */
  @Prop({ type: String, required: true, enum: ['airtime', 'data', 'cable', 'electricity'] })
  type!: string;

  @Prop({
    type: String,
    required: true,
    enum: ['pending', 'success', 'failed'],
    default: 'pending',
  })
  status!: string;

  @Prop({ required: true, min: 0 })
  amount!: number;

  /** Internal reference generated by ajo-server. */
  @Prop({ required: true, unique: true })
  reference!: string;

  /** Reference returned by the external bill payment server. */
  @Prop()
  externalReference?: string;

  /** The service provider (e.g. 'mtn', 'dstv', 'ekedc'). */
  @Prop({ required: true })
  provider!: string;

  /** The recipient identifier (phone, smartCardNumber, meterNumber). */
  @Prop({ required: true })
  recipient!: string;

  /** Extra bill-specific data (dataPlanId, packageName, meterType, disco, etc.). */
  @Prop({ type: Object })
  metadata?: Record<string, unknown>;

  /** Link to the wallet transaction that recorded the debit. */
  @Prop({ type: Types.ObjectId, ref: 'WalletTransaction' })
  walletTransaction?: Types.ObjectId;
}

export const BillTransactionSchema = SchemaFactory.createForClass(BillTransaction);

// Index for listing a user's history reverse-chronologically.
BillTransactionSchema.index({ user: 1, createdAt: -1 });
